version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile  
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/aplicacao
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  nginx:
    build:
        dockerfile: ./docker/web/Dockerfile
        context: .
    image: nginx
    container_name: container-lb
    ports:
        - "80:80"
    depends_on:
      - "web"