name: gces-aplicao-docker-ci
on:
  push:
    branches: "main"

  pull_request:
    branches: "main"
defaults:
  run:
    working-directory: ./aplicacao

jobs:
  build:
    name: build-container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: BUild and up docker containers
        run: docker-compose up --build -d

  run-tests:
    name: run-rails-tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restart rails db
        run: docker-compose run web rails db:reset

      - name: Run tests
        run: docker-compose run web rspec

  run-lint:
    name: run-rails-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint
        run: docker-compose run web bash -c "gem install rubocop; rubocop -A --fail-level F"